### PR TITLE
expose more BBB settings in .env file

### LINKED ISSUE #22: Expose more BBB settings in .env file
This is merely a suggestion, since it can be expected of admins to figure out the appropriate configs files by reading the BBB docs and maintaining a separate branch or writing script to re-apply their configuration after updating the the local checkout.
However the comprehensive .env file that @alangecker provided, already includes a lot of settings and I'd like to discuss, if it would make sense to include a few more, that may be of interest for "bbb-beginners" (like me ^^) and eventually make a BBB-conference feel a bit more like a Jitsi-conference (in terms of UX), while remaining more compatible to most devices than the latter ;)
Also if BBB decides to merge this repo and provide images on dockerhub the .env file might be the most accessible way to configure most non-ui settings persistently.

Proposals:
* Changing the default welcome message in chat. 
It may be confusing to read an English welcome message in an otherwise entirely German user interface. `mod/core/web/bigbluebutton.properties` Setting `defaultWelcomeMessage`
* Option to disable the freeswitch audio announcements, e.g. "You are the only person in this conference". "You are now (un)muted". This audio may be quite confusing to non-english speakers. In my particular case, elderly people around and above the age of 50. 
Remove Files `/usr/share/freeswitch/sounds/en/us/callie/conference/*/*.wav`
* Option to disable the "echo test".
With respect to the ease of use for people not familiar with technicalities like audio checks. My main concern is, that a person who is confused by the audio check, will have a hard time fixing these underlying issue. However a person capable of fixing microphone input issues, doesn't necessarily need the additional audio check to see whether the microphone is working correctly. In that regard an option to disable this feature would be greatly appreciated. 
`mod/html5/settings.yml` Setting `skipCheck: true`
* Option to disable "listenOnly" mode
From people unfamiliar with the concept of BBB and its roots as an education tool (or from other first time users) I have often encountered the question whether they should click the microphone or the headphone to join the conference. Every so often someone intuitively picks the wrong one ...
`mod/html5/settings.yml` Setting `listenOnlyMode: false`
* Option to enable auto sharing the webcam upon loading the room.
For easy of use with first time users, that are not accustomed to the webcam icon, fail to find it or can't discern its disabled state.
`mod/html5/settings.yml` Setting `autoShareWebcam: true`

### PR DESCRIPTION
**Pull request by cjhille**
closes #22

### CODE REVIEW

**Comment by alangecker** [comment]
deleting all the .wav files effects much more than just the known announcements in the html5 client.
It results, for example, in silence on SIP dial in.
I think the prefered way is to simply configure freeswitch in the right way. I archived that with a template.

Additionally I renamed some variables to more understandable names and added default values, so that a existing setup doesn't break on upgrade, when the variables are missing.

now, everything seems fine! :)

thanks for your contribution!

**Comment by cjhille** [comment]
Oh right.. I totally forgot the existing setups that need to be upgraded. And regarding the freeswitch config: I tried, but 
ultimately failed to find a working configuration. Thank you for fixing this and integrating it the proper way :)

Just FYI: The variable names I used were quite awkward and the ones you picked are a lot more decisive (e.g. "SKIP_CHECK" vs "DISABLE_ECHO_TEST"). But I initially chose to stick with the BBB-naming for those properties, so that users can easily find the the corresponding lines within the docs or discussion boards. I suppose giving the more meaningful names might alleviate the need for the latter ^^

**Comment by alangecker** [comment]
> Just FYI: The variable names I used were quite awkward and the ones you picked are a lot more decisive (e.g. "SKIP_CHECK" vs "DISABLE_ECHO_TEST"). But I initially chose to stick with the BBB-naming for those properties, so that users can easily find the the corresponding lines within the docs or discussion boards. I suppose giving the more meaningful names might alleviate the need for the latter ^^

ah, good point!
maybe we could simply add the "official" BBB-names to the comments in `sample.env`?

**Comment by cjhille** [comment]
good idea, maybe something like `[...], refers to / translates to config flag: SKIP_CHECK`

**Pull request merged**
