### PR TITLE
support for v2.3

### PR DESCRIPTION
**Pull request by alangecker**
(this PR is not meant to get merged, just to make changes visible.)

#edit: now moved to https://github.com/bigbluebutton/docker

- removal of `core` and therefore any ubuntu distro :tada:
- removal of red5 and other legacy bbb components
- removal of any dependency on the ubuntu packaging
- `html5` finally on node v12

### How to try out v2.3-alpha
```
$ git fetch
$ git checkout v2.3.x
$ ./scripts/upgrade
```
### Missing for v2.3 Release
- [ ] Stable BigBlueButton v2.3 Release (currently at `v2.3-alpha-3`)
- [x] Rebase on current `v2.2.x` branch
- [x] Docker LibreOffice Integration (Presentation conversion fails at the moment)
- [x] Rewrite of interaction with docker-compose #42  #47
- [ ] Start mutliple html5 instances (introduced in `v2.3-alpha-3`)
- [x] Fix Recording (`v2.3-alpha-3`)
- [ ] Fix _401 Unauthorized: Session not found._ via Greenlight (`v2.3-alpha-3`)

### closes
- #26 Further split up `core` in its individual components
- #27 drop root privileges of bbb-webrtc-sfu
- #42 Avoid using script/compose

### CODE REVIEW

**Comment by cjhille** [comment]
Out of curiosity: Is there currently is any work being done on v2.3.x by the BBB devs? As far as I can tell, 2.3.x branch has been stale for a while now. https://github.com/bigbluebutton/bigbluebutton/tree/2.2.3-candidate-with-issues

**Comment by alangecker** [comment]
> Out of curiosity: Is there currently is any work being done on v2.3.x by the BBB devs? As far as I can tell, 2.3.x branch has been stale for a while now. https://github.com/bigbluebutton/bigbluebutton/tree/2.2.3-candidate-with-issues

this is v2.2.3, not v2.3.x ;)

as far as I see it, `develop` represents the current state of v2.3.x.
https://github.com/bigbluebutton/bigbluebutton/tree/develop

There was even a alpha release few days ago:
https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-alpha-1

**Comment by cjhille** [comment]
Whops ... silly me. Thanks for clearing this up!

**Comment by HosseyNJF** [comment]
Any progress? I'd be glad to contribute to this, if there was a roadmap. IDK what is remaining to do now

**Comment by alangecker** [comment]
@HosseyNJF if you want, you can already use this branch! :)

I've added in the first post all points which are missing right now.
Currently the main point is, that BBB 2.3 is still in an early alpha phase and it might still take a bit until it gets released.

If you want to speed it up, you could check the related Milestone https://github.com/bigbluebutton/bigbluebutton/milestone/23
Apart from that, there is not much to do here - but thanks for asking! :)

**Comment by alangecker** [comment]
Development for the 2.3 branch is now moved to [bigbluebutton/docker](https://github.com/bigbluebutton/docker), means with 2.3 this project becomes the official bbb-docker project :)

**Pull request closed without merging**
