### PR TITLE
+ paragraph "Install into Apache existing setup"

### PR DESCRIPTION
**Pull request by senatoregiorgio**
Added a paragraph that explains how it is possibile to install bbb-docker into an existing Apache setup, to `README.md`. I'm not English, so maybe there are some errors in the text: in that case, please correct them 😄

### CODE REVIEW

**Comment by cjhille** [comment]
I find it very useful, that you share your knowledge to run this BBB build behind an existing apache. Thank you! 

I'm running this build behind jwilders nginx proxy (which takes care of certificates), and I'm also planing to add a PR with a short description about the necessary configuration changes (pretty basic stuff).

Considering the many options how this dockerized build may be integrated, I find this explanation a bit lengthy and I would propose a much shorter text, limited mostly to the apache settings, or maybe even better: Provide the .conf file which can referenced and merely add a short warning about the TURN limitations and required apache modules. 

You could even modify the setup script to take care of required changes in the .env file and print out a final apache conf that can be copy and pasted by the admin. The setup script would be my preferred approach to make this more accessible for alternative server environments.

**Comment by senatoregiorgio** [comment]
I think you're right: maybe this text is a little too long. I'll shorten it as much as possible. I'll also think about modifying the setup script. Thank you for your feedback!

**Comment by alangecker** [comment]
> Considering the many options how this dockerized build may be integrated, I find this explanation a bit lengthy and I would propose a much shorter text, limited mostly to the apache settings, or maybe even better: Provide the .conf file which can referenced and merely add a short warning about the TURN limitations and required apache modules.

I just thought that, considering the probably growing number of manuals, it makes sense to swap them from the README into a separate `docs` folder.

@senatoregiorgio does that look fine for you? and do you consider your instructions as ready to get merged?


> You could even modify the setup script to take care of required changes in the .env file and print out a final apache conf that can be copy and pasted by the admin. The setup script would be my preferred approach to make this more accessible for alternative server environments.

Considering the countless number of different setups I fear a bit, that It might get an unreadable thousand lines script like the [bbb-install.sh](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh)... :D


#edit: the warning about the TURN limitations would be good to have! :)

**Comment by senatoregiorgio** [comment]
It's good to separate installation instructions from additional instructions, like you've just done. My idea is to have a general introduction regarding the installation of bbb-docker into a server which already runs a Web server, then to add different paragraphs for Apache and Nginx or any other common existing setup. I've just proposed a solution in my last commit 😃

Edit: I believe my instructions are ready to get merged, but first we should consider if it would be better to shorten them.

**Comment by nyok92** [comment]
Hi, would it be of any help to use this docker installation behind traefik ? I used to get it working but now with all the work done with nginx auto proxy, i didn't made any change yet on my setup. Thanks for all the good work and help !

**Comment by alangecker** [comment]
> [...] but first we should consider if it would be better to shorten them.

Since it is an separate document, I think it is fine that it is a little bit longer ;)

**Pull request merged**
