### PR TITLE
Replace script/compose with docker-compose

### PR DESCRIPTION
**Pull request by trickert76**
As mentioned in #42 there is the option to use docker-compose as it is. Because you already use a lot of environment variable, all of them can be stored in the .env file and a docker-compose.override.yml can be created.

The main adventage is, that a user can normally call `docker-compose` as it is and can use bash completion etc.

### CODE REVIEW

**Comment by alangecker** [comment]
sorry, for my unresponsiveness! :/
I'm currently quite busy with other work why my participation regarding BBB is currently reduced to a minimum... I will come back on this soon!

**Comment by mooomooo** [comment]
Did you forget to include `conf/setup/docker-compose.init.yml` in the commit?  I can't seem to find it.  

(Also, +1 for this approach)

**Comment by trickert76** [comment]
You're right. My problem is, that I've switched to another workstation and the old one is reinitialized. I though - everything is checked in... I can't find the file. 

But I think, it should only contain two lines (version+service) as some kind of header. I'l try to add it tomorrow. Also I can remove on the conflicts.

**Comment by alangecker** [comment]
heyho :)
1. meanwhile I also support to this!
2. Since this is a breaking change for most installations and v2.3 is upcoming anyway, I think we should release this with v2.3 so people are aware of the point when there are changes to their setup required, so that a `./scripts/upgrade` within v2.2 doesn't break anything.
   * I switched the target branch to `v2.3.x`
   * Unfortunately some rebasing effort might me necessary
3. If we already do a big change: `cat`-ing files can't be the best option possible... :D Isn't there any templating engine which supports conditional blocks without much dependencies? we even could use something like [jinja2docker](https://hub.docker.com/r/dinutac/jinja2docker) during the setup.

**Comment by alangecker** [comment]
the approach from https://github.com/alangecker/bigbluebutton-docker/pull/71#issuecomment-777506431 is now merged, so I consider this PR now as obsolete.

thanks for the impulsions @trickert76 ! :)

**Pull request closed without merging**
