### PR TITLE
Add recording feature

### LINKED ISSUE #4: how can we help for the recording ?
how can we help for the recording ?

### PR DESCRIPTION
**Pull request by artemtech**
Video recording is working, but not for audio yet :(

edit by @alangecker:
closes #4

### CODE REVIEW

**Comment by alangecker** [comment]
seems like quite some effort so far. thanks a lot!

a goal of this project was to avoid having a monolithic container but rather using dockers benefits and splitting the functionality in different containers, which are easier maintainable and more stable.

The path of reaching this goal was to start with the "official" approach ([bigbluebutton/docker](https://github.com/bigbluebutton/docker/tree/v2.2.x)) which I called `core` and isolating step by step parts into there own containers. The idea was that at _the end™_ the `core` container is gone, because all its components are extracted and clearly separated.
This MR now, for the first time, adds components again to `core` which for me personally doesn't feel reasonable since it would mean a step away from this design concept.

Also there are quite a lot of people who are using BBB intentionally without the recording functionality because of privacy concerns (https://github.com/bigbluebutton/bigbluebutton/issues/9202). A separate `recording` container would also provide an easy way for running it optionally.

Can you imagine moving the feature into an own container?
- The easy way probably would be to simple duplicate `core/Dockerfile`, but removing all the `core` things (like `bbb-web`, `red5`, etc.)

During the next two weeks I will be quite busy, but after that I can also help with that task if you don't feel motivated! ;)

**Comment by artemtech** [comment]
oh ok, i'll give it a try to separate recording container,

**Comment by alangecker** [comment]
I've managed to get audio recording! :)

currently freeswitch's `mod_opusfile` in the official freeswitch debian repository can't create a file. there is an open pull request fixing it, but not merged yet: https://github.com/signalwire/freeswitch/pull/719

I now replaced it with the binary from the official bigbluebutton repo and added the `libopusenc0` dependency.

additionally:
- created volumes so `core` has access to freeswitch and kurento's recording files
- fixed etherpad url, so the script is able to collect the pad content (there was an error in the logs)

I did already some work with separating the recording stuff into its own container, I will hopefully finish that in the next days ;)

**Comment by alangecker** [comment]
so, now in a working state with an own container. feel free to review it! :) 

### open tasks
- [x] rebase to current `develop`
- [x] conditional settings based on `ENABLE_RECORDING` in `bigbluebutton.properties` and `html/settings.yml`
- [x] ~improving size of `recordings-process` container~ (rather difficult to achieve. maybe a step for another time!)
- [ ] review!

**Comment by alangecker** [comment]
so, everything is done from my perspective.
Would be anyone up for doing a review? maybe @artemtech? :)

**Comment by alangecker** [comment]
I'm not really sure how/why I apparently closed this PR?^^

**Comment by congthang1** [comment]
Is this working? Lol

**Comment by artemtech** [comment]
i have tested it and works well in my setup.

**Comment by staukini** [comment]
Nice work @artemtech and @alangecker !

Thanks a lot - can't wait for a merge to the main branch.

**Comment by senatoregiorgio** [comment]
Thank you very much for implementing this feature! 🙂

When are you going to merge this pull request to the master branch? 🚀

**Comment by alangecker** [comment]
### It is finally so far! :tada: 

(will be included in the main `v2.2.x` branch with the [Release v2.2.23-1](https://github.com/alangecker/bigbluebutton-docker/pull/55))

**Comment by alangecker** [comment]
argh @artemtech 
i've just seen (after merging) that you later added some changes which aren't related to that recording feature.
I'll revert them again for the [Release v2.2.23-1](https://github.com/alangecker/bigbluebutton-docker/pull/55), but feel free to open new Pull Requests for them! :)

**Pull request merged**
