### PR TITLE
template based generation of docker-compose.yml

### LINKED ISSUE #42: Avoid using script/compose
I think, your project is a much better approach to dockerize BBB or wait for a new BBB version that supports Ubuntu 18.04 or 20.04.

I think, the way, you integrate the optional nginx and coturn isn't ideal. I think, it would be "nicer" to have only the docker-compose.yml and (which is supported out of the box from docker-compose) an additional docker-compose.override.yml (see https://devilbox.readthedocs.io/en/latest/configuration-files/docker-compose-override-yml.html). 

I would change the setup script in a way, that it cats/echos/pipes the content of the docker-compose.*.yml into the docker-compose.override.yml, when the user says 'y' in the script. So, instead of

    if [ ! "$https_proxy" == "y" ]
    then
        sed -i "s/ENABLE_HTTPS_PROXY.*/#ENABLE_HTTPS_PROXY=true/" .env
    fi
    ...

do a:

    rm docker-compose.override.yml && touch docker-compose.override.yml
    if [ "$https_proxy" == "y" ]
    then
        cat docker-compose.https.yml >> docker-compose.override.yml
    fi
    
    if [ "$greenlight" == "y" ]
    then
        cat docker-compose.greenlight.yml >> docker-compose.override.yml
    fi
    
    if [ "$coturn" == "y" ]
    then
        cat docker-compose.coturn.yml >> docker-compose.override.yml
    fi

In that case a user can just use `docker-compose` in the root directory of the project.

After reviewing the code, there are several other things to do:

- there is no setup question for webhooks and demo but a docker-compose.*.yml exists. The `compose` looks for the webhooks but that is only enabled manually.
- also cat'ing the corresponding YAML file into the override may end with a wrong syntax, because of multiple main-nodes 'version', 'services' etc. so, the compose files should only contain the diff or use somekind of patch-mechanism.

I'm switching (personally) to a Jinja template together with Ansible. That works too (because the script cannot be used easy in Ansible because of the question-answer-format without params).

### PR DESCRIPTION
**Pull request by alangecker**
@trickert76 brought up (#42) concerns regarding the current way of conditionally combining multiple docker-compose.yml blocks which brings multiple disadvantages raised in https://github.com/alangecker/bigbluebutton-docker/issues/42#issuecomment-666287442

he/she worked already on a alternative way (#47) which uses `cat` to generate a single `docker-compose.yml` file.

I thought, that `cat`ing files together can't be the best way we can find so I start hereby a different approach:
- a `./scripts/generate-compose` script which utilizes `jwilder/dockerize` to generate a docker-compose.yml based on a template
- golang templates, since it is already used on multiple places in this project (#dockerize)
- zero new dependencies on the host system

missing:
- [x] get feedback! and maybe rethink it
- [ ] test everything
- [x] more variable checks (e.g. `ENABLE_COTURN` can't work without `ENABLE_HTTPS_PROXY` due to missing certificates)
- [x] update `README.md`
- [ ] add changelog entry
- [x] add to `./scripts/upgrade`

 
----- 
closes #42  #47

### CODE REVIEW

**Comment by trickert76** [comment]
I think, this is a good aproach. I don't know golang templates (coming from Ansible Jinja, Velocity). But at the end - it is a template and that is good and better way then the cat mechanism. 

About the problem with ENABLE_COTURN without HTTPS. Either add the condition that coturn only works with the HTTPS_ENBALED flag or add a simple certbot container or let generate a self signed certificate only in that case inside the COTURN server.  With Letsencrypt there must be a port 80 open and that is maybe the reason why somebody is not enabling HTTPS (because they use a different LB in front).

So - I'm waiting for the merge. ;-)

**Comment by clawoflight** [comment]
I like this as well, thank you very much for your effort :)

**Comment by till** [comment]
I think instead of using `cat`, you could do:

```
docker-compose -f first-compose.yml -f second-compose.yml up
```

... and it would merge for you. No need to combine the files, and maybe no need for a _new_ templating language?

**Comment by alangecker** [comment]
@till
chaining `docker-compose.yml` was our starting point and it is what is used right now ;)
https://github.com/alangecker/bigbluebutton-docker/blob/v2.2.x/scripts/compose

but with having 7 compose files it would become quite a messy command, so I introduced this `./scripts/compose` wrapper, which leads to new issues @trickert76 pointed out in #42 

the golang templating language is already used in multiple places, so It would not be a new language added:
```
mod/core/web/bigbluebutton.properties
mod/core/web/turn-stun-servers.xml
mod/core/bbb-apps-akka/application.conf
mod/webhooks/config.yml
mod/recordings/bigbluebutton.yml
mod/html5/settings.yml
mod/freeswitch/conf/vars.xml.tmpl
mod/freeswitch/conf/autoload_configs/conference.conf.xml.tmpl
```

**Comment by alangecker** [comment]
Due to some merge conflicts, I recreated the commit and pushed in directly to `v2.3.x` with
https://github.com/alangecker/bigbluebutton-docker/commit/16df9ab33482de33b9be17ec099f9c6c020c7308

so this is effectively finally merged :tada:! :)

**Pull request closed without merging**
